# Generated by Django 4.2.6 on 2025-10-09 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessOwnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, help_text='The full name of the business owner.', max_length=200)),
                ('business_name', models.CharField(blank=True, help_text='The official name of the business.', max_length=200)),
                ('upi_id', models.CharField(blank=True, help_text='The UPI ID where the business owner receives payments.', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The full name of the customer.', max_length=200)),
                ('email', models.EmailField(blank=True, help_text="The customer's email address (for email reminders).", max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, help_text="The customer's phone number in E.164 format (e.g., +919876543210).", max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='core.businessownerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(help_text="A brief description of the deal, e.g., 'Wedding Photoshoot'.", max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text='The total amount due for this deal.', max_digits=10)),
                ('due_date', models.DateField(help_text='The date the payment is due.')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', help_text='The current status of the payment.', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='core.customer')),
            ],
        ),
        migrations.CreateModel(
            name='ReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(help_text="The method used for the reminder (e.g., 'Email', 'WhatsApp').", max_length=20)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='core.deal')),
            ],
        ),
    ]
